name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  octave:
    name: GNU Octave
    runs-on: ubuntu-latest
    container: gnuoctave/octave:9.2.0
    steps:
      - uses: actions/checkout@v7
      - name: Run tests
        run: octave-cli --eval "cd tests; runTests"
      - name: Run scripts
        run: octave-cli --eval "cd tests; runScripts"

  matlab:
    name: MATLAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: matlab-actions/setup-matlab@v3
      - name: Run tests
        uses: matlab-actions/run-command@v3
        with:
          command: cd tests; runTests
      - name: Run scripts
        uses: matlab-actions/run-command@v3
        with:
          command: cd tests; runScripts
